// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void ui_event_Slider1(lv_event_t * e); //背光
void ui_event_Switch4(lv_event_t * e);
void LOGO_Animation(lv_obj_t * TargetObject, int delay);
void dropdown_Animation(lv_obj_t * TargetObject, int delay);
void deopupward_Animation(lv_obj_t * TargetObject, int delay);
void dropbutton_Animation(lv_obj_t * TargetObject, int delay);
void gesture_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_ScreenLOGO
void ui_ScreenLOGO_screen_init(void);
void ui_event_ScreenLOGO(lv_event_t * e);
extern lv_obj_t * ui_ScreenLOGO;
extern lv_obj_t * ui_Image3;
// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
void ui_event_ScreenHome(lv_event_t * e);
extern lv_obj_t * ui_ScreenHome;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Panel3;
void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
void ui_event_Panel5(lv_event_t * e);
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label4;
void ui_event_Panel7(lv_event_t * e);
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Bar1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label3;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Slider1;
// SCREEN: ui_ScreenSet
void ui_ScreenSet_screen_init(void);
void ui_event_ScreenSet(lv_event_t * e);
extern lv_obj_t * ui_ScreenSet;
extern lv_obj_t * ui_Label8;
void ui_event_Panel9(lv_event_t * e);
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image11;
void ui_event_Panel11(lv_event_t * e);
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image13;
void ui_event_Panel13(lv_event_t * e);
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Image15;
void ui_event_Panel8(lv_event_t * e);
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Image21;
void ui_event_Panel10(lv_event_t * e);
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Image22;
void ui_event_Panel12(lv_event_t * e);
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Image14;
// SCREEN: ui_ScreenSetWallpaper
void ui_ScreenSetWallpaper_screen_init(void);
void ui_event_ScreenSetWallpaper(lv_event_t * e);
extern lv_obj_t * ui_ScreenSetWallpaper;
extern lv_obj_t * ui_Label11;
void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
void ui_event_Image7(lv_event_t * e);
extern lv_obj_t * ui_Image7;
void ui_event_Image12(lv_event_t * e);
extern lv_obj_t * ui_Image12;
void ui_event_Image17(lv_event_t * e);
extern lv_obj_t * ui_Image17;
void ui_event_Image18(lv_event_t * e);
extern lv_obj_t * ui_Image18;
void ui_event_Image19(lv_event_t * e);
extern lv_obj_t * ui_Image19;
// SCREEN: ui_ScreenSetIP
void ui_ScreenSetIP_screen_init(void);
void ui_event_ScreenSetIP(lv_event_t * e);
extern lv_obj_t * ui_ScreenSetIP;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Roller3;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label17;
// SCREEN: ui_ScreenSetGesture
void ui_ScreenSetGesture_screen_init(void);
void ui_event_ScreenSetGesture(lv_event_t * e);
extern lv_obj_t * ui_ScreenSetGesture;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label20;
// SCREEN: ui_ScreenSetabout
void ui_ScreenSetabout_screen_init(void);
void ui_event_ScreenSetabout(lv_event_t * e);
extern lv_obj_t * ui_ScreenSetabout;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
// SCREEN: ui_ScreenCATBOX
void ui_ScreenCATBOX_screen_init(void);
void ui_event_ScreenCATBOX(lv_event_t * e);
extern lv_obj_t * ui_ScreenCATBOX;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Switch4;
void ui_event_Keyboard2(lv_event_t * e);
extern lv_obj_t * ui_Keyboard2;
// SCREEN: ui_ScreenSetUpdate
void ui_ScreenSetUpdate_screen_init(void);
void ui_event_ScreenSetUpdate(lv_event_t * e);
extern lv_obj_t * ui_ScreenSetUpdate;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label40;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label44;
// SCREEN: ui_ScreenSetLAW
void ui_ScreenSetLAW_screen_init(void);
void ui_event_ScreenSetLAW(lv_event_t * e);
extern lv_obj_t * ui_ScreenSetLAW;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_TextArea1;
// SCREEN: ui_ScreenScreen
void ui_ScreenScreen_screen_init(void);
extern lv_obj_t * ui_ScreenScreen;
void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_bootlogo_png);    // assets/bootlogo.png
LV_IMG_DECLARE(ui_img_wallpaper1_png);    // assets/wallpaper1.png
LV_IMG_DECLARE(ui_img_iconset_png);    // assets/iconSet.png
LV_IMG_DECLARE(ui_img_iconscreen_png);    // assets/iconScreen.png
LV_IMG_DECLARE(ui_img_iconcatbox_png);    // assets/iconCATbox.png
LV_IMG_DECLARE(ui_img_dropkey_png);    // assets/dropKey.png
LV_IMG_DECLARE(ui_img_dropkmbox_png);    // assets/dropKMBOX.png
LV_IMG_DECLARE(ui_img_492698769);    // assets/brightness-.png
LV_IMG_DECLARE(ui_img_arrow_png);    // assets/arrow.png
LV_IMG_DECLARE(ui_img_small1_png);    // assets/small1.png
LV_IMG_DECLARE(ui_img_small2_png);    // assets/small2.png
LV_IMG_DECLARE(ui_img_wallpaper2_png);    // assets/wallpaper2.png
LV_IMG_DECLARE(ui_img_small3_png);    // assets/small3.png
LV_IMG_DECLARE(ui_img_wallpaper3_png);    // assets/wallpaper3.png
LV_IMG_DECLARE(ui_img_small4_png);    // assets/small4.png
LV_IMG_DECLARE(ui_img_wallpaper4_png);    // assets/wallpaper4.png
LV_IMG_DECLARE(ui_img_small5_png);    // assets/small5.png
LV_IMG_DECLARE(ui_img_wallpaper5_png);    // assets/wallpaper5.png
LV_IMG_DECLARE(ui_img_small6_png);    // assets/small6.png
LV_IMG_DECLARE(ui_img_wallpaper6_png);    // assets/wallpaper6.png
LV_IMG_DECLARE(ui_img_gesture_png);    // assets/gesture.png
LV_IMG_DECLARE(ui_img_aboutbj_png);    // assets/aboutbj.png



LV_FONT_DECLARE(ui_font_FontChina24);
LV_FONT_DECLARE(ui_font_FontChina48);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
