// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_WHITE 0
#define UI_THEME_COLOR_ASH 1
#define UI_THEME_COLOR_BUTTBG 2
#define UI_THEME_COLOR_BACKGROUNDGREY 3

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_white[1];
extern const ui_theme_variable_t _ui_theme_alpha_white[1];

extern const ui_theme_variable_t _ui_theme_color_ash[1];
extern const ui_theme_variable_t _ui_theme_alpha_ash[1];

extern const ui_theme_variable_t _ui_theme_color_buttbg[1];
extern const ui_theme_variable_t _ui_theme_alpha_buttbg[1];

extern const ui_theme_variable_t _ui_theme_color_BackgroundGrey[1];
extern const ui_theme_variable_t _ui_theme_alpha_BackgroundGrey[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
