// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenSetGesture_screen_init(void)
{
    ui_ScreenSetGesture = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSetGesture, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ScreenSetGesture, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackgroundGrey);
    ui_object_set_themeable_style_property(ui_ScreenSetGesture, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackgroundGrey);

    ui_Label19 = lv_label_create(ui_ScreenSetGesture);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, -340);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "手势");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_FontChina48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image16 = lv_img_create(ui_ScreenSetGesture);
    lv_img_set_src(ui_Image16, &ui_img_gesture_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image16, -200);
    lv_obj_set_y(ui_Image16, 0);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_ScreenSetGesture);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, 130);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "手势向右或者手势向左返回上一级");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_FontChina24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenSetGesture, ui_event_ScreenSetGesture, LV_EVENT_ALL, NULL);

}
