// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenSetWallpaper_screen_init(void)
{
    ui_ScreenSetWallpaper = lv_obj_create(NULL);
    lv_obj_add_flag(ui_ScreenSetWallpaper, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_set_flex_flow(ui_ScreenSetWallpaper, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ScreenSetWallpaper, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    ui_object_set_themeable_style_property(ui_ScreenSetWallpaper, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackgroundGrey);
    ui_object_set_themeable_style_property(ui_ScreenSetWallpaper, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackgroundGrey);
    lv_obj_set_style_pad_left(ui_ScreenSetWallpaper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenSetWallpaper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenSetWallpaper, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenSetWallpaper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ScreenSetWallpaper, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ScreenSetWallpaper, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_ScreenSetWallpaper);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, -400);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "选择图片");
    lv_obj_add_flag(ui_Label11, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_font(ui_Label11, &ui_font_FontChina48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_ScreenSetWallpaper);
    lv_img_set_src(ui_Image2, &ui_img_small1_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 192
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_ScreenSetWallpaper);
    lv_img_set_src(ui_Image7, &ui_img_small2_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 192
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_img_create(ui_ScreenSetWallpaper);
    lv_img_set_src(ui_Image12, &ui_img_small3_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 192
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_img_create(ui_ScreenSetWallpaper);
    lv_img_set_src(ui_Image17, &ui_img_small4_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 192
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image18 = lv_img_create(ui_ScreenSetWallpaper);
    lv_img_set_src(ui_Image18, &ui_img_small5_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 192
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image19 = lv_img_create(ui_ScreenSetWallpaper);
    lv_img_set_src(ui_Image19, &ui_img_small6_png);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 192
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image2, ui_event_Image2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image7, ui_event_Image7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image12, ui_event_Image12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image17, ui_event_Image17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image18, ui_event_Image18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image19, ui_event_Image19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenSetWallpaper, ui_event_ScreenSetWallpaper, LV_EVENT_ALL, NULL);

}
