// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenSetLAW_screen_init(void)
{
    ui_ScreenSetLAW = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSetLAW, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ScreenSetLAW, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackgroundGrey);
    ui_object_set_themeable_style_property(ui_ScreenSetLAW, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackgroundGrey);

    ui_Label41 = lv_label_create(ui_ScreenSetLAW);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 0);
    lv_obj_set_y(ui_Label41, -340);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "法律声明");
    lv_obj_add_flag(ui_Label41, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_font(ui_Label41, &ui_font_FontChina48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_ScreenSetLAW);
    lv_obj_set_width(ui_TextArea1, 480);
    lv_obj_set_height(ui_TextArea1, 700);
    lv_obj_set_x(ui_TextArea1, 0);
    lv_obj_set_y(ui_TextArea1, 100);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1,
                         "法律声明\n本店所提供的喵喵派开发板及其相关软件、硬件、以及网站内容，仅能在同意以下免责声明时方可使用。如果您不希望遵守这些条款，请停止使用本店的产品。在使用（下载）喵喵派开发板、硬件或本网站时，即视为您已同意以下规定（以下称“使用条款”），并同意遵守本使用条款并受其约束。且您已满18周岁或已获得家长或监护人的同意，同时您有完全民事能力接受本使用条款。本声明所包含的信息可能随时被修改，恕不另行通知，我们不保证该信息没有错误。如果贵方发现任何问题，请书面通知我们。\n\n危险应用领域声明\n本店提供的喵喵派开发板及相关软件或硬件是为在各类普通技术应用领域内的一般使用而开发的。它不应被应用于任何存在危险性或可能造成伤害的应用领域，包括但不限于核能设施、航空器导航或通信系统、直接支撑生命的设备或武器系统的开发、设计、制造或使用。若在这些危险应用领域使用喵喵派开发板及相关软件或硬件，贵方应负责采取所有适当的防范措施，并对可能产生的任何损失或损害承担全部责任。本店对此不承担任何责任。\n\n免责声明\n凡是访问、浏览本店铺（包括线上及线下店铺）并购买喵喵派开发板及其相关产品的用户，均应先仔细阅读并理解本声明内容。一经购买即视为购买者已知情并同意本声明内容。\n\n喵喵派开发板是一款可编程的开发板，无需安装驱动，软件发送命令至设备后，设备将执行相应操作。广泛应用于教育、科研、自动化测试、个人项目等普通领域。本店特别声明，任何购买该产品的购买者均应当将此产品用于合法用途，本店不对因非法用途所产生的任何法律问题及法律后果承担任何法律责任。\n\n根据《中华人民共和国民法典》、《中华人民共和国网络安全法》的相关规定，公民主体均享有个人信息保护权以及隐私权，购买者禁止以使用开发板产品开发非法或违背公共秩序、善良风俗的行为，违者将自行承担法律后果。\n\n特此声明！\n\n");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea1, &ui_font_FontChina24, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_ScreenSetLAW, ui_event_ScreenSetLAW, LV_EVENT_ALL, NULL);

}
